Algoritmo "Multiplicação"
// Dado um valor, calcular e exibir o dobro do valor.
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/01/2023
Var
// Seção de Declarações das variáveis 
n1, multiplicacao: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite o valor: ")
Leia(n1)

multiplicacao <- (n1*2)
EscrevaL("O dobro doo valor é: ", multiplicacao)

Fimalgoritmo