Algoritmo "operadores_logicos"
// 
//Operadores Logicos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/01/2023
Var
// Seção de Declarações das variáveis 
a, b, c: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a<- 2
b<- 3
c<- 5
Escreval((a=b) e (a=c))
Escreval((a<b) e (a<>c) e (b<>c))
Escreval((a<>b) ou (c>a+c))
Escreval((c=a+b) ou (c=a-b))

Fimalgoritmo