Algoritmo "Somatória"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/02/2023
Var
// Seção de Declarações das variáveis 
cont, num, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

soma<-0

Para cont<-1 ate 5 faca
    Escreva("Entre com um valor: ")
    Leia(num)
    soma<-soma+num
FimPara
     Escreval("A somatória dos valores: ", soma)

Fimalgoritmo